name: Sync Posts to Typesense

on:
  schedule:
    # Runs daily at 12:30 AM PH time (UTC+8) = 16:30 UTC
    - cron: "30 16 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: production # ✅ This enables access to "Production" secrets

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run Typesense Sync
        run: npm run sync:typesense
        env:
          TYPESENSE_HOST: ${{ secrets.TYPESENSE_HOST }}
          TYPESENSE_PORT: ${{ secrets.TYPESENSE_PORT }}
          TYPESENSE_PROTOCOL: ${{ secrets.TYPESENSE_PROTOCOL }}
          TYPESENSE_API_KEY: ${{ secrets.TYPESENSE_API_KEY }}
